### ISSUE TITLE
Incorrect bin files in the wiki.

### ISSUE THREAD

**Issue by ero589** [HomeKidd/ESP8266-Homekit-Smart-Blinds#1]
Thanks for this awesome project.
I was attempting to flash my D1 mini with the smart blinds code but it actually flashed to the Air Quality Sensor bin. I assumed the bin files got mixed from the other HomeKidd projects

**Comment by HomeKidd** [comment]
This issue has been resolved, one link is pointed to wrong .bin file! Thanks!
But you can always the latest release in the [Releases tab](https://github.com/HomeKidd/ESP8266-Homekit-Smart-Blinds/releases)!
